JqueryDapper/Controllers/AuthenticationController.cs
using System;
using System.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JqD.Common.ILogic;
using JqD.Common.Web;
using JqueryDapper.ViewModels;

namespace JqueryDapper.Controllers
{
    public class AuthenticationController : BaseController
    {
        private readonly ISystemUserLogic _systemUserLogic;
        private static readonly string ApplicationDomain = ConfigurationManager.AppSettings["ApplicationDomain"];

        public AuthenticationController(ISystemUserLogic systemUserLogic)
            : base(systemUserLogic)
        {
            _systemUserLogic = systemUserLogic;
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginCommand command)
        {
            var loginUser = _systemUserLogic.Login(command.UserName, command.Password);
            FormsAuthenticateUser(loginUser.SystemUserId + "_" + Guid.NewGuid());
            return Json(new { Success = true });
        }

        public ActionResult LogOut(string returnUrl)
        {
            //if (Request.Url != null)
            //{
            //    var aCookie = new HttpCookie("JqDLastVisit")
            //    {
            //        Path = "/",
            //        Value = Request.Url.ToString(),
            //        Expires = DateTime.Now.AddDays(1),
            //        Domain = ApplicationDomain,
            //        HttpOnly = false
            //    };
            //    Response.Cookies.Add(aCookie);
            //}
            FormsAuthentication.SignOut();
            var myCookie = new HttpCookie(FormsAuthentication.FormsCookieName)
            {
                Domain = ApplicationDomain,
                Expires = DateTime.Now.ToUniversalTime().AddDays(-1d)
            };
            Response.Cookies.Add(myCookie);
            _systemUserLogic.LogOut(LoginUser.LoginName);
            return Redirect(JqD.Common.Helper.UrlHelper.WebUrl());
        }

        private void FormsAuthenticateUser(string userId)
        {
            //设置用户的 cookie 的值
            var cookie = FormsAuthentication.GetAuthCookie(userId, false);

            if (string.IsNullOrEmpty(ApplicationDomain))
            {

            }
            cookie.Domain = ApplicationDomain;
            cookie.Expires = DateTime.Now.ToUniversalTime().AddDays(1d);
            Response.Cookies.Add(cookie);
        }
    }
}

JqueryDapper/Controllers/SystemManage/SystemUserController.cs
using System.Linq;
using System.Web.Mvc;
using JqD.Common.Command.SystemManage;
using JqD.Common.ILogic;
using JqD.Common.Web;
using JqD.Entities.QueryModels;
using JqD.Infrustruct;
using JqueryDapper.ViewModels.SystemManage;

namespace JqueryDapper.Controllers.SystemManage
{
    public class SystemUserController : BaseController
    {
        private readonly ISystemUserLogic _systemUserLogic;

        public SystemUserController(ISystemUserLogic systemUserLogic)
            :base(systemUserLogic)
        {
            _systemUserLogic = systemUserLogic;
        }

        public ActionResult Index(string loginName, int pageNo = 1)
        {
            var startNo = (pageNo - 1) * Pagination.PageNumber + 1;
            var queryParams = new QuerySystemUserModel
            {
                LoginName = loginName,
                StartNo = startNo,
                Rows = Pagination.PageNumber,
                Page = pageNo
            };
            int totleCount;
            var list = _systemUserLogic.QueryByPage(queryParams, out totleCount);
            var model = new SystemUsersPageViewModel
            {
                SystemUsers = list.Select(x => new SystemUserViewModel
                {
                    Id = x.Id,
                    LoginName = x.LoginName,
                    Password = x.Password
                }).ToList(),
                Pagination = new Pagination(startNo, Pagination.PageNumber, totleCount)
            };
            return View("~/Views/SystemManage/SystemUser.cshtml", model);
        }

        [HttpPost]
        public ActionResult Add(AddUserCommand user)
        {
            _systemUserLogic.Add(user);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            _systemUserLogic.Delete(id);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Update(UpdateUserCommand user)
        {
            _systemUserLogic.Update(user);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Get(int id)
        {
            var result=_systemUserLogic.Get(id);
            return Json(result);
        }
    }
}

JqueryDapper/Controllers/Work/WorkController.cs
using System.Linq;
using System.Web.Mvc;
using JqD.Command.Work;
using JqD.Common.ILogic;
using JqD.Common.Web;
using JqD.ILogic;
using JqD.Infrustruct;
using JqueryDapper.ViewModels.Work;

namespace JqueryDapper.Controllers.Work
{
    public class WorkController : BaseController
    {
        private readonly IBlogArticleLogic _blogArticleLogic;

        public WorkController(ISystemUserLogic systemUserLogic, 
            IBlogArticleLogic blogArticleLogic)
            :base(systemUserLogic)
        {
            _blogArticleLogic = blogArticleLogic;
        }

        public ActionResult Index(int pageNo = 1)
        {
            var startNo = (pageNo - 1) * Pagination.PageNumber + 1;
            int totleCount;
            var list = _blogArticleLogic.QueryByPage(startNo, pageNo * Pagination.PageNumber, out totleCount);
            var model = new WorkPageViewModel
            {
                Works = list.Select(x => new WorkViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    Category = x.Category,
                    Remark= x.Remark,
                    CreateUser = x.CreateUser,
                    CreateDate = x.CreateDate.ToString("yyyy-MM-dd")
                }).ToList(),
                Pagination = new Pagination(startNo, Pagination.PageNumber, totleCount),
            };
            return View("~/Views/Work/Work.cshtml", model);
        }

        [HttpPost]
        public ActionResult Add(AddWorkCommand work)
        {
            _blogArticleLogic.Add(work);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            _blogArticleLogic.LogicDelete(id);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Update(UpdateWorkCommand work)
        {
            _blogArticleLogic.Update(work);
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Get(int id)
        {
            var result = _blogArticleLogic.Get(id);
            return Json(result);
        }
    }
}

JqueryDapper/Views/Shared/_Footer.cshtml
<footer>
    <div class="zerogrid wrap-footer">
        <div class="row">
            <div class="col-1-3 col-footer-1">
                <div class="wrap-col">
                    <h3>About</h3>
                    <a href="@Url.Action("Index","Home")">
                        <img src="/images/Style/avatar.jpg" alt=""/></a>
                    <p>Ut volutpat consectetur aliquam. Curabitur auctor in nis ulum ornare. Sed consequat, augue condimentum fermentum gravida, metus elit vehicula dui.</p>
                </div>
            </div>
            <div class="col-1-3 col-footer-2">
                <div class="wrap-col">
                    <h3>Categories</h3>
                    <ul>
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Romantic</a></li>
                        <li><a href="#">Cartoon</a></li>
                        <li><a href="#">Zombies</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-1-3 col-footer-3">
                <div class="wrap-col">
                    <h3>Location</h3>
                    <div class="wrap-map"></div>
                </div>
            </div>

        </div>
    </div>
    <div class="zerogrid copyright">
        <div class="wrapper">
            <ul class="quick-link f-right">
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms of Use</a></li>
            </ul>
        </div>
    </div>
</footer>

JqueryDapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css", "~/Content/LayoutCSS")
    @Scripts.Render("~/bundles/jquery", "~/bundles/bootstrap", "~/bundles/modernizr", "~/bundles/LayoutJS")
</head>
<body>
    @Html.Partial("_Top")
    <div>
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
    @RenderSection("scripts", required: false)
</body>
</html>

JqueryDapper/Views/Shared/_Top.cshtml
@using System.Diagnostics
@{
    Debug.Assert(Request.Url != null, "Request.Url != null");
    var requestUrl = Request.Url.ToString();
}
<div id="cssmenu" class="align-center">
    <ul class="top_menu">
        <li class="active Home"><a href="@Url.Action("Index", "Home")"><span>Home</span></a></li>
        <li class="has-sub Blog">
            <a href="javascript:void(0)"><span>Blog</span></a>
            <ul>
                <li class="has-sub">
                    <a><span>Work</span></a>
                    <ul>
                        <li><a href="@Url.Action("Index", "Work")"><span>Work</span></a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="has-sub System">
            <a href="javascript:void(0)"><span>System</span></a>
            <ul>
                <li><a href="@Url.Action("Index", "SystemUser")"><span>SystemUser</span></a></li>
                <li><a href="@Url.Action("LogOut", "Authentication")"><span>LogOut</span></a></li>
            </ul>
        </li>
    </ul>
</div>
<header>
    <div class="logo">
        <a href="#"><img src="/images/Style/logo.png" alt="" /></a>
    </div>
</header>
<script type="text/javascript">
    var requestUrl = '@requestUrl'.split("/").pop();
    if (requestUrl === "") {
        requestUrl = "Home";
    }
    else if (requestUrl.indexOf("SystemUser")>-1) {
        requestUrl = "System";
    }
    else {
        requestUrl = "Blog";
    }
    $(".top_menu > li").removeClass("active");
    $(`.${requestUrl}`).addClass("active");
</script>